name: Publish Landing Content
on:
  push:
    branches: ['main']
jobs:
  build-and-deploy:
    uses: curvenote/actions/.github/workflows/push.yml@v1
    with:
      landing-content: agrogeo
    secrets:
      CURVENOTE: ${{ secrets.CURVENOTE_TOKEN }}